version: '3.8'

services:
  app:
    build: .
    ports:
      - "8083:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=productdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - product-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=productdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - product-network

networks:
  product-network:
    driver: bridge

volumes:
  postgres-data: